baseURL = "https://nottsjs.org"
languageCode = "en-gb"
title = "NottsJS"
buildFuture = true
publishDir = "docs"
disableKinds = ["taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT", "404"]
relativeURLs = true
